  name: android-recovery-action
  uses: XenonTheInertG/android-recovery-action@v2.1.2
  env:
    MANIFEST: "https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0-deprecated"
    DT_LINK: "https://github.com/momenabdulrazek/android_device_Nokia_PDA.git"
    VENDOR: "Nokia"
    CODENAME: "pda"
    KERNEL_LINK: ""
    TARGET: "bootimage"
    FLAVOR: "eng"
    EXTRA_CMD: ""
    TZ: "Cairo/Egypt"
